const Images = {
  emptyImage: null,
  loadingBG: require('../assets/img/loadingBG.png'),
  logoWhite: require('../assets/img/logo-white.png'),
  splashScreenLogoWhite: require('../assets/img/logo-white-v2.png'),
  logoDarkGreen: require('../assets/img/logo-darkgreen.png'),
  logoGray: require('../assets/img/logo-gray.png'),
  logoLoading: require('../assets/img/logo-loading.png'),
  logoTeal: require('../assets/img/logo-teal.png'),
  logoTealSmall: require('../assets/img/Nestabl-logo-teal-small.png'),
  logoMedGreenSmall: require('../assets/img/Nestabl-logo-medgreen-small.png'),
  profileBg: require('../assets/img/profile-bg.jpg'),

  feed01: require('../assets/img/feed-1.jpg'),
  feed02: require('../assets/img/feed-2.jpg'),
  feed03: require('../assets/img/feed-3.jpg'),
  feed04: require('../assets/img/feed-4.jpg'),
  feed05: require('../assets/img/feed-5.png'),
  feed06: require('../assets/img/feed-6.jpg'),
  feed07: require('../assets/img/feed-7.jpg'),
  feed08: require('../assets/img/feed-8.jpg'),
  feed09: require('../assets/img/feed-9.jpg'),
  feed10: require('../assets/img/feed-10.jpg'),
  feed11: require('../assets/img/feed-11.jpg'),
  feed12: require('../assets/img/feed-12.jpg'),
  feed13: require('../assets/img/feed-13.jpg'),
  feed14: require('../assets/img/feed-14.jpg'),
  feed15: require('../assets/img/feed-15.jpg'),
  feed16: require('../assets/img/feed-16.jpg'),

  nestablWelcome01: require('../assets/img/nestabl_welcome1.png'),
  nestablWelcome02: require('../assets/img/nestabl_welcome2.png'),
  nestablWelcome03: require('../assets/img/nestabl_welcome3.png'),
  nestablWelcome04: require('../assets/img/nestabl_welcome4.png'),
  nestablWelcome05: require('../assets/img/nestabl_welcome5.png'),
  nestablWelcome06: require('../assets/img/nestabl_welcome6.png'),

  tipBG: require('../assets/img/tip-bg.jpg'),
  appIcon: require('../assets/img/appicon.jpg'),
  skipNext: require('../assets/img/skip_next.png'),
  skipPrev: require('../assets/img/skip_previous.png'),
  pause: require('../assets/img/pause.png'),
  playCircle: require('../assets/img/play_circle.png'),
};

export default Images;
