const constants = {
  UI_UPDATE: 'UI_UPDATE',
  UI_BROADCAST_UPDATE: 'UI_BROADCAST_UPDATE',

  AUTH_INIT: 'AUTH_INIT',
  AUTH_UPDATE: 'AUTH_UPDATE',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  SETTING_BULK_UPDATE: 'SETTING_BULK_UPDATE',
  SETTING_PATCH: 'SETTING_PATCH',

  FEED_FETCH_VIDEOS: 'FEED_FETCH_VIDEOS',
  FEED_FETCH_VIDEOS_PENDING: 'FEED_FETCH_VIDEOS_PENDING'
};

export default constants;
